sudo: required
language: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - cd ${TRAVIS_BUILD_DIR}
  - pip install flask
  - pip install flask-babel
  - pip install flask-mail
  - pip install . -vvv
  - pip install codecov pytest pytest-cov

script: python -m pytest --cov=igem_tuebingen_website .


after_success:
  - codecov

notifications:
  email:
    recipients:
      - lukas.heumos@posteo.net
    on_success: never
    on_failure: always